name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
  

    steps:
    - uses: actions/checkout@v3
    - name: Compile CSS and Javascript
      run: |
        npm ci
        npm run prod

    - name: Configure PHP 8.1
      uses: shivammathur/setup-php@master
      with:
        php-version: 8.1
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
  
    - name: Composer install
      run: | 
        composer install --no-dev --no-interaction --prefer-dist
    - name: Create deployment artifact
      run: tar -czf app.tar.gz *
    - name: Create deployment artifact
      run: tar -czf app.tar.gz --exclude=*.git --exclude=node_modules --exclude=tests *
    - name: Create deployment artifact
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *
